"""empty message

Revision ID: 151bf21a1c3e
Revises: 75bd9b022fb7
Create Date: 2017-11-07 19:44:55.187403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151bf21a1c3e'
down_revision = '75bd9b022fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('feed_article_id', sa.String(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_article_id'], [u'feed_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feed_article_id')
    )
    op.add_column(u'users', sa.Column('is_premium_user', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'is_premium_user')
    op.drop_table('user_articles')
    # ### end Alembic commands ###
