"""empty message

Revision ID: 2f0bcc3c0679
Revises: dfb8d7f1442c
Create Date: 2017-10-30 17:22:01.936703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0bcc3c0679'
down_revision = 'dfb8d7f1442c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_articles', sa.Column('duck_rank', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_articles', 'duck_rank')
    # ### end Alembic commands ###
