"""empty message

Revision ID: 35913076027e
Revises: ab1ecbeed176
Create Date: 2017-10-26 13:35:04.309307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35913076027e'
down_revision = 'ab1ecbeed176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_article_details', sa.Column('feed_article_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feed_article_details', 'feed_articles', ['feed_article_id'], ['id'], ondelete=u'CASCADE')
    op.drop_column('feed_article_details', 'top_image')
    op.drop_column('feed_article_details', 'sentiment')
    op.drop_column('feed_article_details', 'keyword')
    op.drop_column('feed_article_details', 'summary')
    op.add_column('feed_articles', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('feed_articles', sa.Column('sentiment', sa.SmallInteger(), nullable=True))
    op.add_column('feed_articles', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_articles', 'summary')
    op.drop_column('feed_articles', 'sentiment')
    op.drop_column('feed_articles', 'image')
    op.add_column('feed_article_details', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feed_article_details', sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feed_article_details', sa.Column('sentiment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('feed_article_details', sa.Column('top_image', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feed_article_details', type_='foreignkey')
    op.drop_column('feed_article_details', 'feed_article_id')
    # ### end Alembic commands ###
