"""empty message

Revision ID: ab1ecbeed176
Revises: 03da332617c3
Create Date: 2017-10-26 13:27:28.652678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab1ecbeed176'
down_revision = '03da332617c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_article_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_image', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=255), nullable=True),
    sa.Column('rich_rank', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('country_rank', sa.Integer(), nullable=True),
    sa.Column('author', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], [u'feeds.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feed_article_Details')
    op.add_column('feed_articles', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('feed_articles', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_articles', 'rank')
    op.drop_column('feed_articles', 'keywords')
    op.create_table('feed_article_Details',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"feed_article_Details_id_seq"\'::regclass)'), nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('top_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rich_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], [u'feeds.id'], name=u'feed_article_Details_feed_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'feed_article_Details_pkey')
    )
    op.drop_table('feed_article_details')
    # ### end Alembic commands ###
