"""empty message

Revision ID: b4ccd29aedb1
Revises: bfa2daa184d2
Create Date: 2017-10-26 15:51:25.276036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ccd29aedb1'
down_revision = 'bfa2daa184d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('feed_updated_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'feed_updated_at')
    # ### end Alembic commands ###
