"""empty message

Revision ID: bfa2daa184d2
Revises: 
Create Date: 2017-10-26 15:38:00.417077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfa2daa184d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.SmallInteger(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], [u'feeds.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_category',
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], )
    )
    op.create_table('feed_article_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('rich_rank', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('country_rank', sa.Integer(), nullable=True),
    sa.Column('movie', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('feed_article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_article_id'], [u'feed_articles.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_article_details')
    op.drop_table('feed_category')
    op.drop_table('feed_articles')
    op.drop_table('feeds')
    op.drop_table('categories')
    # ### end Alembic commands ###
