"""empty message

Revision ID: c10024ca5685
Revises: c2a1035ea517
Create Date: 2017-10-24 15:32:17.541930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10024ca5685'
down_revision = 'c2a1035ea517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_category',
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], )
    )
    op.drop_table('feed_article_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_article_category',
    sa.Column('feed_article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categories'], [u'categories.id'], name=u'feed_article_category_categories_fkey'),
    sa.ForeignKeyConstraint(['feed_article_id'], [u'feed_articles.id'], name=u'feed_article_category_feed_article_id_fkey')
    )
    op.drop_table('feed_category')
    # ### end Alembic commands ###
