"""empty message

Revision ID: c2a1035ea517
Revises: f40e40c4a495
Create Date: 2017-10-24 12:46:00.130729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2a1035ea517'
down_revision = 'f40e40c4a495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=70), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], [u'feeds.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_article_category',
    sa.Column('feed_article_id', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['feed_article_id'], ['feed_articles.id'], )
    )
    op.add_column(u'feeds', sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False))
    op.add_column(u'feeds', sa.Column('icon', sa.Text(), nullable=True))
    op.add_column(u'feeds', sa.Column('title', sa.Text(), nullable=True))
    op.add_column(u'feeds', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column(u'feeds', 'last_updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'feeds', sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column(u'feeds', 'updated_at')
    op.drop_column(u'feeds', 'title')
    op.drop_column(u'feeds', 'icon')
    op.drop_column(u'feeds', 'created_at')
    op.drop_table('feed_article_category')
    op.drop_table('feed_articles')
    op.drop_table('categories')
    # ### end Alembic commands ###
