"""empty message

Revision ID: c997b3c0b612
Revises: b4ccd29aedb1
Create Date: 2017-10-26 19:37:42.471412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c997b3c0b612'
down_revision = 'b4ccd29aedb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_articles', sa.Column('share_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_articles', 'share_count')
    # ### end Alembic commands ###
