"""empty message

Revision ID: d387ba0b2980
Revises: b6ab4a73a266
Create Date: 2017-11-02 19:31:24.266617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd387ba0b2980'
down_revision = 'b6ab4a73a266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('app_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feeds', 'apps', ['app_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'app_id')
    # ### end Alembic commands ###
