"""empty message

Revision ID: ded2145e4568
Revises: 151bf21a1c3e
Create Date: 2017-11-10 17:23:37.856968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded2145e4568'
down_revision = '151bf21a1c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('alexa_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'alexa_rank')
    # ### end Alembic commands ###
