"""empty message

Revision ID: dfb8d7f1442c
Revises: c997b3c0b612
Create Date: 2017-10-30 17:19:50.225982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb8d7f1442c'
down_revision = 'c997b3c0b612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('reset_pin', sa.SmallInteger(), server_default=sa.text(u'(0)::smallint'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('is_god', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('confirmation_code', sa.String(length=255), nullable=True),
    sa.Column('last_login_location', sa.JSON(), nullable=True),
    sa.Column('is_password_change_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('slack_id', sa.String(length=30), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'feed_articles', sa.Column('published_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'feed_articles', 'published_at')
    op.drop_table('user_tokens')
    op.drop_table('user_details')
    op.drop_table('users')
    # ### end Alembic commands ###
