"""empty message

Revision ID: fc5571904fd7
Revises: 9b4ec4994a66
Create Date: 2017-11-05 15:10:08.292733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5571904fd7'
down_revision = '9b4ec4994a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_article_details', 'feed_article_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'feed_article_details', 'feed_articles', ['feed_article_id'], ['id'], ondelete=u'CASCADE')
    op.alter_column('feed_articles', 'feed_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'feed_articles', 'feeds', ['feed_id'], ['id'], ondelete=u'CASCADE')
    op.create_foreign_key(None, 'feed_category', 'feeds', ['feed_id'], ['id'])
    op.alter_column('feeds', 'app_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'feeds', 'apps', ['app_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.alter_column('feeds', 'app_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'feed_category', type_='foreignkey')
    op.drop_constraint(None, 'feed_articles', type_='foreignkey')
    op.alter_column('feed_articles', 'feed_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'feed_article_details', type_='foreignkey')
    op.alter_column('feed_article_details', 'feed_article_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
